server:
  port: 8090
  servlet:
    context-path: /common

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    #(服务的提供者是需要注册到注册中心的) 默认就是true
    register-with-eureka: true
    service-url:
      #配置高可用eureka服务地址
      defaultZone: http://${eureka.instance.hostname}:8091/eureka,http://${eureka.instance.hostname}:8099/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true


#当前服务名称
spring:
  application:
    name: eureka-common-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率值介于0到1之间，1表示全部采集
      probability: 1
# DataSource Config
#  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:test
#    username: root
#    password: root


jwt:
  config:
    key: test
    ttl: 3600000