server:
  port: 8099
  servlet:
    context-path: /config

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    #(服务的提供者是需要注册到注册中心的) 默认就是true
    register-with-eureka: true
    service-url:
      #配置高可用eureka服务地址
      defaultZone: http://${eureka.instance.hostname}:8091/eureka,http://${eureka.instance.hostname}:8099/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true


#当前服务名称
spring:
  profiles:
    #使用本地存储配置
    active: native
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        native:
          # 本地资源目录/src/main/resource/properties
          search-locations: classpath:properties/
  #        git:
  #          #git地址                                 
  #          uri: https:git/zlj
  #          username:  zwx475996
  #          password:  SDVtest@159
  #MQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        # 指定刷新地址
        include: bus-refresh
